#
# Metrics services -- provides a web GUI to monitor Lighthouse nodes.
#
version: "3.3"

services:
    prometheus:
        build:
            context: prometheus
        volumes:
            - prometheus-data:/prometheus
            - type: bind
              source: ./scrape-targets
              target: /prometheus/targets
        restart: always
        network_mode: host
    grafana:
        build:
            context: grafana
        volumes:
            - grafana-data:/var/lib/grafana
        restart: always
        network_mode: host
    loki:
        build:
            context: loki
        ports:
            - "127.0.0.1:3100:3100"
        volumes:
            - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
            - loki-data:/data/loki
        restart: always
        network_mode: host       
    promtail:
        build:
            context: promtail        
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
        restart: always
        network_mode: host       
        
volumes:    
    grafana-data:
    prometheus-data:
    loki-data:
    targets:
