{
 "title": "Validator Logs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Validator Layer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"validator\"}"
    }
   ]
  },
  {
   "title": "Consensus Layer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"consensus\"}"
    }
   ]
  },
  {
   "title": "Execution Layer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container_name=\"execution\"}"
    }
   ]
  }
 ]
}